apiVersion: v1
kind: ReplicationController 
metadata:
  name: rest-api-rc 
spec:
  replicas: 5
  selector:
    app: rest-api-app
  template:
    metadata:
      labels:
        app: rest-api-app
    spec:
      containers:
      - name: rest-api-image 
        image: aasrith1906/rest-api-image:latest
        ports:
        - containerPort: 5000